// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/samims/merchant-api/app/models"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// UserRepoMock is an autogenerated mock type for the UserRepo type
type UserRepoMock struct {
	mock.Mock
}

// FindOne provides a mock function with given fields: _a0, _a1
func (_m *UserRepoMock) FindOne(_a0 context.Context, _a1 models.User) (*models.User, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(context.Context, models.User) *models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0, _a1
func (_m *UserRepoMock) GetAll(_a0 context.Context, _a1 models.UserQuery) ([]models.User, int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []models.User
	if rf, ok := ret.Get(0).(func(context.Context, models.UserQuery) []models.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, models.UserQuery) int64); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, models.UserQuery) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *UserRepoMock) Save(_a0 context.Context, _a1 *models.User) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *UserRepoMock) Update(_a0 context.Context, _a1 *models.User, _a2 []string) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User, []string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepoMock creates a new instance of UserRepoMock. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepoMock(t testing.TB) *UserRepoMock {
	mock := &UserRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
